### ISSUE TITLE
Has anybody tried Sequoia?

### ISSUE THREAD

**Issue by vasi** [Rybo713/X1C6-macOS#5]
I haven't given it a shot yet myself, maybe it'll just work!

**Comment by Rybo713** [comment]
macOS Sequoia 15.1 is now supported.

**Comment by DocMAX** [comment]
Wifi ist not working on Sequoia

**Comment by mgrimace** [comment]
> Wifi ist not working on Sequoia

~~were you able to get it working? Mine is greyed out during sequoia setup. AC 8265 (original card)~~
Installed without internet, then installed Heliport app, working fine
